@startuml
class Tema {
    - nome: String
    - fundo: String
    - texto: String
    - botao_fundo: String
    - botao_texto: String
}

class RelogioDigital {
    - tema: Tema
    - master: Master
    - label_relogio: Label
    - label_data: Label
    - master: Master

    + __init__(master: Master, tema: Tema)
    + atualizar_horario()
    + aplicar_tema(novo_tema: Tema)
}

class GerenciadorTemas {
    - temas: Map<String, Tema>
    - tema_atual: String

    + __init__()
    + obter_tema(nome: String): Tema
    + alternar_tema(): Tema
}

class BotaoTema {
    - gerenciador: GerenciadorTemas
    - callback: Callback
    - tema: Tema

    + __init__(master: Master, gerenciador: GerenciadorTemas, callback: Callback)
    + atualizar_aparencia(tema: Tema)
}

class RelogioApp {
    - janela: Janela
    - gerenciador_temas: GerenciadorTemas
    - container: Frame
    - relogio: RelogioDigital
    - botao_tema: BotaoTema

    + __init__(janela: Janela)
    + criar_widgets()
    + alternar_tema()
}

RelogioDigital *-- Tema : utiliza
RelogioDigital *-- Master : extende
BotaoTema *-- GerenciadorTemas : utiliza
RelogioApp *-- GerenciadorTemas : possui
RelogioApp *-- RelogioDigital : possui
RelogioApp *-- BotaoTema : possui
@enduml